### ISSUE TITLE
Question: Referencing higher-level properties in if-then-else constructs

### ISSUE THREAD

**Issue by nictas** [json-schema-org/json-schema-spec#760]
**Background:**

I'm working on an application that deploys groups of microservices in different cloud platforms (Cloud Foundry, Kubernetes) based on a set of YAML files that describe the configurations of the microservices and their interdependencies. The YAML files follow the same [schema](http://json.schemastore.org/mtad) for both Cloud Foundry and Kubernetes, while also allowing the users to specify platform specific configurations in a property called "parameters". Examples:
- Cloud Foundry
```
platform: cf
modules:
  - name: orders
    type: application
    requires:
      - name: users
        properties:
          USERS_URL: ~{url}
    parameters: # This is the important part
       buildpack: https://github.com/cloudfoundry/java-buildpack.git
       host: users
```
- Kubernetes
```
platform: kubernetes
modules:
  - name: orders
    type: application
    requires:
      - name: users
        properties:
          USERS_URL: ~{url}
    parameters: # This is the important part
       image: https://hub.docker.com/r/exampleman/echo-app
       container-port: 80
```
As you can see, the two YAML files differ only based on their "parameters" sections, which must essentially comply to different schemas.

**Problem:**

We want to have one schema that describes the general structure of the document and N others, that describe the structures of the "parameters" sections based on the platform. We already have the first schema published [here](http://json.schemastore.org/mtad), but we're now wondering how we could pick the correct "parameters" schema based on the "platform" field of the document.

I read about [if/then/else sections](https://json-schema.org/understanding-json-schema/reference/conditionals.html) and [JSON pointers](https://json-schema.org/understanding-json-schema/reference/conditionals.html), but what I failed to understand is whether or not conditions could check the values of higher-level properties in the document.
This is the given example:
```
{
  "type": "object",
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "enum": ["United States of America", "Canada"]
    }
  },
  "if": {
    "properties": { "country": { "const": "United States of America" } }
  },
  "then": {
    "properties": { "postal_code": { "pattern": "[0-9]{5}(-[0-9]{4})?" } }
  },
  "else": {
    "properties": { "postal_code": { "pattern": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" } }
  }
}
```
But here the if condition checks the "country" property of the same object it's in. What we want to do, is something similar to:
```
{
  "type": "object",
  "properties": {
    "platform": {
      "enum": ["cf", "kubernetes"]
    },
    "modules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "parameters": {
            "type": "object",
            "if": {
              "/platform": { "const": "cf" }
            },
            "then": {
              "$ref": "cf-parameters.json#/parameters"
            },
            "else": {
              "$ref": "kubernetes-parameters.json#/parameters"
            }
          }
        }
      }
    }
  }
}
```
Note the "/platform" in the "if" condition. This is how a JSON pointer to the "platform" property would look like, right?

Apologies if I've misunderstood or missed anything. My knowledge on JSON schemas is limited to what I've read today. :)
