### ISSUE TITLE
Positional and optional item in array ?

### ISSUE THREAD

**Issue by alfredking1988** [json-schema-org/json-schema-spec#894]
Currently, the JSON Schema seems only to allow rear optional items through `additionalItems`. 

Is it possible to allow **positional optional items**? 

Such as this imaginary schema:
```js
{
  "type": "array",
  "items": [
    {
      // user must provide a nickname
      "type": "string"
    },
    {
      // the age is personal, so it is OPTIONAL
      // "optional": true,
      "type": "number"
    },
    {
      // user must provide a email
      "type": "string"
    }
  ]
}
```
Given the above imaginary schema, the following values are both valid：
`['Tom', 30, 'tom@example.com']`: Tom provide all the info, including the optional age.
`['Alice', 'alice@example.com']`: Alice does not provide the optional age.

Of course, the schema author must ensure the mutually exclusive between the positional-optional item and the following item. In the example above, the positional-optional `age`'s type is `number`, the `email`'s type is `string`, they are mutually exclusive, so the schema is unambiguous.

**Comment by notEthan** [comment]
positions in json schema `items` are fixed to the corresponding numeric index, so you'll need different schemas for different permutations of the indices. something like (yaml):

```yaml
oneOf:
  - items:
      - {type: string, description: "name"}
      - {type: number, description: "age"}
      - {type: string, description: "email"}
  - items:
      - {type: string, description: "name"}
      - {type: string, description: "email"}
```

that should use $refs to avoid duplication, but even still, it would rapidly get out of hand if you have multiple optional elements. arrays where elements can appear at varying indices are not a kind of structure that json-schema is all that well-suited to describe.
